# **Librerias**

In [1]:
# Importamos 

import torch
import sympy 
import warnings

from torch.func import jacrev
from sympy.printing import latex
from IPython.display import display, Math

# Logging 

warnings.filterwarnings('ignore', category = UserWarning)

# Version 

print(f'Sympy Version: {sympy.__version__}')
print(f'Pytorch Version: {torch.__version__}')

Sympy Version: 1.13.1
Pytorch Version: 2.5.1+cpu


# **Gradiente**

### **Ejercicio #1**

**Funcion:**

$$F(X) = \text{Tr}(XA)$$

**Derivada:**

$$df(X) = \text{Tr}(AdX)$$

**Gradiente:** 

$$(\nabla X)^T = A$$
$$\nabla X = A^T$$

In [2]:
# Definimos los coeficientes de ambas matrices

a1, a2, a3, a4, a5, a6 = sympy.symbols(names = 'a_{1} a_{2} a_{3} a_{4} a_{5} a_{6}')
x1, x2, x3, x4, x5, x6 = sympy.symbols(names = 'x_{1} x_{2} x_{3} x_{4} x_{5} x_{6}')

# Definimos las matrices

A = sympy.Matrix([[a1, a2], [a3, a4], [a5, a6]])
X = sympy.Matrix([[x1, x2, x3], [x4, x5, x6]])

# Definimos la Funcion Escalar

fn = sympy.trace(X @ A)

# Calculamos el Gradiente Simbolico 

gradient_symbolic_teory_1 = sympy.Matrix.zeros(X.shape[0], X.shape[1])
gradient_symbolic_teory_2 = sympy.Matrix.zeros(X.shape[0], X.shape[1])

for row in range(0, X.shape[0]):
    for col in range(0, X.shape[1]):
        gradient_symbolic_teory_1[row, col] = sympy.Symbol(fr"\frac{{\partial F}}{{\partial X_{{{row+1},{col+1}}}}}")
        gradient_symbolic_teory_2[row, col] = sympy.Symbol(fr"\frac{{\partial F}}{{\partial {X[row, col]}}}")
        
gradient_symbolic_latex_1 = r"\begin{bmatrix}" + r" \\".join(" & ".join(str(gradient_symbolic_teory_1[row, col]) for col in range(X.shape[1])) + r" \\[1pt]" for row in range(X.shape[0])) + r"\end{bmatrix}"
gradient_symbolic_latex_2 = r"\begin{bmatrix}" + r" \\".join(" & ".join(str(gradient_symbolic_teory_2[row, col]) for col in range(X.shape[1])) + r" \\[1pt]" for row in range(X.shape[0])) + r"\end{bmatrix}"

# Calculamos el Gradiente

gradient = sympy.Matrix.zeros(X.shape[0], X.shape[1])

for row in range(0, X.shape[0]):
    for col in range(0, X.shape[1]):
        gradient[row, col] = sympy.diff(fn, X[row, col])
        
# Calculamos el Gradiente por Formula

gradient_formula = A.T

# Visualizamos 

print('Funcion Escalar:')
display(Math('F(X) = {Tr}(XA)'))
print(f'\n')
print('Definicion de Matrices:')
display(Math(f"A = {latex(A)}, \\quad X = {latex(X)}"))
print(f'\n')
print(f'Operacion #1:')
display(Math('C = X \cdot A'))
display(Math(f"C = {latex(X @ A)}"))
print(f'\n')
print(f'Salida de la Funcion Escalar:')
display(Math('F(X) = {Tr}(C)'))
display(Math(f"F(X) = {latex(fn)}"))
print(f'\n')
print(f'Gradiente Simbolico:')
display(Math(r"\nabla_X = " + gradient_symbolic_latex_1))
display(Math(r"\nabla_X = " + gradient_symbolic_latex_2))
display(Math(r"\nabla_X = " + latex(gradient)))
print(f'\n')
print(f'Gradiente Formula:')
display(Math(r"\nabla_X = A^T"))
display(Math(r"\nabla_X = " + latex(gradient_formula)))

Funcion Escalar:


<IPython.core.display.Math object>



Definicion de Matrices:


<IPython.core.display.Math object>



Operacion #1:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Salida de la Funcion Escalar:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Gradiente Simbolico:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>



Gradiente Formula:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [3]:
# Definimos las Matrices

X = torch.tensor([[1.0, 2.0, 7.0], [3.0, 4.0, 9.0]], requires_grad = True)
A = torch.tensor([[2.0, 8.0], [6.0, 1.0], [4.0, 3.0]], requires_grad = False)

# Definimos la Funcion Escalar

def fn(X, A):
    
    output = torch.trace(torch.matmul(X, A)) 
    
    return output 

# Calculamos el Gradiente 

gradient = jacrev(fn, argnums = 0)(X, A)

# Visualizamos un ejemplo numerico

print(f'El Gradiente Respecto a X: \n{gradient}')

El Gradiente Respecto a X: 
tensor([[2., 6., 4.],
        [8., 1., 3.]])


### **Ejercicio #2**

**Funcion:**

$$F(X) = \text{Tr}(XXA)$$

**Derivada:**

$$df(X) = \text{Tr}(AXdX) +  \text{Tr}(XAdX)$$

**Gradiente:** 

$$(\nabla X)^T = AX + XA$$
$$\nabla X = (AX + XA)^T$$

In [4]:
# Definimos los coeficientes de ambas matrices

a1, a2, a3, a4, a5, a6, a7, a8, a9 = sympy.symbols(names = 'a_{1} a_{2} a_{3} a_{4} a_{5} a_{6} a_{7} a_{8} a_{9}')
x1, x2, x3, x4, x5, x6, x7, x8, x9 = sympy.symbols(names = 'x_{1} x_{2} x_{3} x_{4} x_{5} x_{6} x_{7} x_{8} x_{9}')

# Definimos las matrices

A = sympy.Matrix([[a1, a2, a3], [a4, a5, a6], [a7, a8, a9]])
X = sympy.Matrix([[x1, x2, x3], [x4, x5, x6], [x7, x8, x9]])

# Definimos la Funcion Escalar

fn = sympy.trace(X @ X @ A)

# Calculamos el Gradiente Simbolico 

gradient_symbolic_teory_1 = sympy.Matrix.zeros(X.shape[0], X.shape[1])
gradient_symbolic_teory_2 = sympy.Matrix.zeros(X.shape[0], X.shape[1])

for row in range(0, X.shape[0]):
    for col in range(0, X.shape[1]):
        gradient_symbolic_teory_1[row, col] = sympy.Symbol(fr"\frac{{\partial F}}{{\partial X_{{{row+1},{col+1}}}}}")
        gradient_symbolic_teory_2[row, col] = sympy.Symbol(fr"\frac{{\partial F}}{{\partial {X[row, col]}}}")
        
gradient_symbolic_latex_1 = r"\begin{bmatrix}" + r" \\".join(" & ".join(str(gradient_symbolic_teory_1[row, col]) for col in range(X.shape[1])) + r" \\[1pt]" for row in range(X.shape[0])) + r"\end{bmatrix}"
gradient_symbolic_latex_2 = r"\begin{bmatrix}" + r" \\".join(" & ".join(str(gradient_symbolic_teory_2[row, col]) for col in range(X.shape[1])) + r" \\[1pt]" for row in range(X.shape[0])) + r"\end{bmatrix}"

# Calculamos el Gradiente

gradient = sympy.Matrix.zeros(X.shape[0], X.shape[1])

for row in range(0, X.shape[0]):
    for col in range(0, X.shape[1]):
        gradient[row, col] = sympy.diff(fn, X[row, col])
        
# Calculamos el Gradiente por Formula

gradient_formula = (A @ X + X @ A).T

# Visualizamos 

print('Funcion Escalar:')
display(Math('F(X) = {Tr}(XXA)'))
print(f'\n')
print('Definicion de Matrices:')
display(Math(f"A = {latex(A)}, \\quad X = {latex(X)}"))
print(f'\n')
print(f'Operacion #1:')
display(Math('C = X \cdot X'))
display(Math(f"C = {latex(X @ X)}"))
print(f'\n')
print(f'Operacion #2:')
display(Math('D = C \cdot A'))
display(Math(f"D = {latex(X @ X @ A)}"))
print(f'\n')
print(f'Salida de la Funcion Escalar:')
display(Math('F(X) = {Tr}(D)'))
display(Math(f"F(X) = {latex(fn)}"))
print(f'\n')
print(f'Gradiente Simbolico:')
display(Math(r"\nabla_X = " + gradient_symbolic_latex_1))
display(Math(r"\nabla_X = " + gradient_symbolic_latex_2))
display(Math(r"\nabla_X = " + latex(gradient)))
print(f'\n')
print(f'Gradiente Formula:')
display(Math(r"\nabla_X = (AX + XA)^T"))
display(Math(r"\nabla_X = " + latex(gradient_formula)))

Funcion Escalar:


<IPython.core.display.Math object>



Definicion de Matrices:


<IPython.core.display.Math object>



Operacion #1:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Operacion #2:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Salida de la Funcion Escalar:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Gradiente Simbolico:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>



Gradiente Formula:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [5]:
# Definimos las Matrices

X = torch.tensor([[1.0, 2.0, 7.0], [3.0, 4.0, 9.0], [5.0, 4.0, 1.0]], requires_grad = True)
A = torch.tensor([[5.0, 2.0, 5.0], [1.0, 7.0, 2.0], [5.0, 1.0, 1.0]], requires_grad = False)

# Definimos la Funcion Escalar

def fn(X, A):
    
    output = torch.trace(torch.matmul(torch.matmul(X, X), A))
    
    return output 

# Calculamos el Gradiente 

gradient = jacrev(fn, argnums = 0)(X, A)

# Visualizamos un ejemplo numerico

print(f'El Gradiente Respecto a X: \n{gradient}')

El Gradiente Respecto a X: 
tensor([[ 78.,  96.,  47.],
        [ 61.,  81.,  57.],
        [ 74., 104.,  79.]], grad_fn=<ViewBackward0>)


### **Ejercicio #3**

**Funcion:**

$$F(X) = \, \|X\|_F^2$$
$$\, \|X\|_F^2 = \text{Tr}(X X^T)$$

**Derivada:**

$$df(X) = \text{Tr}(X^TdX) +  \text{Tr}(X^TdX)$$

**Gradiente:** 

$$(\nabla X)^T = X^T + X^T = 2X^T$$
$$\nabla X = 2X$$

In [6]:
# Definimos los coeficientes de la matriz

x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12 = sympy.symbols(names = 'x_{1} x_{2} x_{3} x_{4} x_{5} x_{6} x_{7} x_{8} x_{9} x_{10} x_{11} x_{12}')

# Definimos la matriz

X = sympy.Matrix([[x1, x2, x3, x4], [x5, x6, x7, x8], [x9, x10, x11, x12]])

# Definimos la Funcion Escalar

fn = sympy.trace(X @ X.T)

# Calculamos el Gradiente Simbolico 

gradient_symbolic_teory_1 = sympy.Matrix.zeros(X.shape[0], X.shape[1])
gradient_symbolic_teory_2 = sympy.Matrix.zeros(X.shape[0], X.shape[1])

for row in range(0, X.shape[0]):
    for col in range(0, X.shape[1]):
        gradient_symbolic_teory_1[row, col] = sympy.Symbol(fr"\frac{{\partial F}}{{\partial X_{{{row+1},{col+1}}}}}")
        gradient_symbolic_teory_2[row, col] = sympy.Symbol(fr"\frac{{\partial F}}{{\partial {X[row, col]}}}")
        
gradient_symbolic_latex_1 = r"\begin{bmatrix}" + r" \\".join(" & ".join(str(gradient_symbolic_teory_1[row, col]) for col in range(X.shape[1])) + r" \\[1pt]" for row in range(X.shape[0])) + r"\end{bmatrix}"
gradient_symbolic_latex_2 = r"\begin{bmatrix}" + r" \\".join(" & ".join(str(gradient_symbolic_teory_2[row, col]) for col in range(X.shape[1])) + r" \\[1pt]" for row in range(X.shape[0])) + r"\end{bmatrix}"

# Calculamos el Gradiente

gradient = sympy.Matrix.zeros(X.shape[0], X.shape[1])

for row in range(0, X.shape[0]):
    for col in range(0, X.shape[1]):
        gradient[row, col] = sympy.diff(fn, X[row, col])
        
# Calculamos el Gradiente por Formula

gradient_formula = 2 * X

# Visualizamos 

print('Funcion Escalar:')
display(Math('F(X) = {Tr}(X X^T)'))
print(f'\n')
print('Definicion de Matrices:')
display(Math(f"X = {latex(X)}"))
print(f'\n')
print(f'Operacion #1:')
display(Math('C = X \cdot X^T'))
display(Math(f"C = {latex(X @ X.T)}"))
print(f'\n')
print(f'Salida de la Funcion Escalar:')
display(Math('F(X) = {Tr}(C)'))
display(Math(f"F(X) = {latex(fn)}"))
print(f'\n')
print(f'Gradiente Simbolico:')
display(Math(r"\nabla_X = " + gradient_symbolic_latex_1))
display(Math(r"\nabla_X = " + gradient_symbolic_latex_2))
display(Math(r"\nabla_X = " + latex(gradient)))
print(f'\n')
print(f'Gradiente Formula:')
display(Math(r"\nabla_X = 2X"))
display(Math(r"\nabla_X = " + latex(gradient_formula)))

Funcion Escalar:


<IPython.core.display.Math object>



Definicion de Matrices:


<IPython.core.display.Math object>



Operacion #1:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Salida de la Funcion Escalar:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Gradiente Simbolico:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>



Gradiente Formula:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [7]:
# Definimos Nuestra Matriz

X = torch.tensor([[1.0, 2.0, 7.0, 5.0], [3.0, 4.0, 9.0, 1.0], [5.0, 4.0, 1.0, 3.0], [9.0, 5.0, 7.0, 2.0]], requires_grad = True)

# Definimos la Funcion Escalar

def fn(X):
    
    output = torch.norm(X)**2
    
    return output 

# Calculamos el Gradiente 

gradient = jacrev(fn, argnums = 0)(X)

# Visualizamos un ejemplo numerico

print(f'El Gradiente Respecto a X: \n{gradient}')

El Gradiente Respecto a X: 
tensor([[ 2.,  4., 14., 10.],
        [ 6.,  8., 18.,  2.],
        [10.,  8.,  2.,  6.],
        [18., 10., 14.,  4.]], grad_fn=<ViewBackward0>)


# **Jacobiana**

### **Ejercicio #1**

**Funcion:**

$$F(X) = X^2$$

**Derivada:**

$$d(X) = (I \otimes X + X^T \otimes I) \cdot vec(dX)$$

**Jacobiana:** 

$$J = I \otimes X + X^T \otimes I$$

In [8]:
# Definimos los coeficientes de la matriz

x1, x2, x3, x4 = sympy.symbols(names = 'x_{1} x_{2} x_{3} x_{4}')

# Definimos la matriz

X = sympy.Matrix([[x1, x2], [x3, x4]])

# Definimos la Funcion Vectorial

fn = X @ X

# Calculamos la Jacobiana Simbolica 

jacobian_symbolic_teory_1 = sympy.Matrix.zeros(X.shape[0] * fn.shape[0], X.shape[1] * fn.shape[1])
jacobian_symbolic_teory_2 = sympy.Matrix.zeros(X.shape[0] * fn.shape[0], X.shape[1] * fn.shape[1])

for row_output in range(fn.shape[0]):
    for col_output in range(fn.shape[1]):
        for row_input in range(X.shape[0]):
            for col_input in range(X.shape[1]):
                
                jacobian_row = row_output * fn.shape[1] + col_output
                jacobian_col = row_input * X.shape[1] + col_input
                
                jacobian_symbolic_teory_1[jacobian_row, jacobian_col] = sympy.Symbol(fr"\frac{{\partial F_{{{col_output+1},{row_output+1}}}}}{{\partial X_{{{col_input+1},{row_input+1}}}}}")
                jacobian_symbolic_teory_2[jacobian_row, jacobian_col] = sympy.Symbol(fr"\frac{{\partial F_{{{col_output+1},{row_output+1}}}}}{{\partial {X[col_input, row_input]}}}")

jacobian_symbolic_latex_1 = r"\begin{bmatrix}" + r" \\[5pt]".join(" & ".join(str(jacobian_symbolic_teory_1[row, col]) for col in range(jacobian_symbolic_teory_1.shape[1]))
                                                                  for row in range(jacobian_symbolic_teory_1.shape[0])) + r"\end{bmatrix}"

jacobian_symbolic_latex_2 = r"\begin{bmatrix}" + r" \\[5pt]".join(" & ".join(str(jacobian_symbolic_teory_2[row, col]) for col in range(jacobian_symbolic_teory_2.shape[1]))
                                                                  for row in range(jacobian_symbolic_teory_2.shape[0])) + r"\end{bmatrix}"

# Calculamos la Jacobiana

jacobian = sympy.Matrix.zeros(fn.shape[0] * fn.shape[1], X.shape[0] * X.shape[1])

for row_output in range(fn.shape[0]):
    for col_output in range(fn.shape[1]):
        for row_input in range(X.shape[0]):
            for col_input in range(X.shape[1]):
                
                jacobian_row = row_output * fn.shape[1] + col_output
                jacobian_col = row_input * X.shape[1] + col_input
                
                jacobian[jacobian_row, jacobian_col] = sympy.diff(fn[col_output, row_output], X[col_input, row_input])

# Calculamos la Jacobiana por Formula

I = sympy.Matrix.eye(X.shape[0])

jacobian_formula = sympy.kronecker_product(I, X) + sympy.kronecker_product(X.T, I)

# Visualizamos resultados

print('Funcion Vectorial:')
display(Math('F(X) = X \cdot X'))
print(f'\n')
print('Definicion de Matrices:')
display(Math(f"X = {latex(X)}"))
print(f'\n')
print(f'Salida de la Funcion Vectorial:')
display(Math('F(X) = X \cdot X'))
display(Math(f"F(X) = {latex(fn)}"))
print(f'\n')
print('Jacobiana Simbolica:')
display(Math(r"J_X = " + jacobian_symbolic_latex_1))
display(Math(r"J_X = " + jacobian_symbolic_latex_2))
display(Math(r"J_X = " + latex(jacobian)))
print(f'\n')
print('Jacobiana Formula:')
display(Math(r"J_X = I \otimes X + X^T \otimes I"))
display(Math(r"J_X = " + latex(jacobian_formula)))

Funcion Vectorial:


<IPython.core.display.Math object>



Definicion de Matrices:


<IPython.core.display.Math object>



Salida de la Funcion Vectorial:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Jacobiana Simbolica:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>



Jacobiana Formula:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [9]:
# Definimos Nuestra Matriz

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# Definimos la Funcion Vectorial

def Fn(X):   
    
    output = torch.matmul(X, X)
    
    return output 

# Calculamos la Matriz Jacobiana 

jacobian = jacrev(Fn, argnums = 0)(X)

# Redimensionamos (Cada sub-matrix de salida representa una columna de la matriz jacbianda definitiva)

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos un ejemplo numerico

print(f'La Jacobiana Respecto a X: \n{jacobian}')

La Jacobiana Respecto a X: 
tensor([[2., 2., 3., 0.],
        [3., 5., 0., 3.],
        [2., 0., 5., 2.],
        [0., 2., 3., 8.]])


### **Ejercicio #2**

**Funcion:**

$$F(X) = XAX$$

**Derivada:**

$$d(X) = (I \otimes XA + (AX)^T \otimes I) \cdot vec(dX)$$

**Jacobiana:** 

$$J = I \otimes XA + (AX)^T \otimes I$$

In [10]:
# Definimos los coeficientes de ambas matrices

a1, a2, a3, a4 = sympy.symbols(names = 'a_{1} a_{2} a_{3} a_{4}')
x1, x2, x3, x4 = sympy.symbols(names = 'x_{1} x_{2} x_{3} x_{4}')

# Definimos las matrices

A = sympy.Matrix([[a1, a2], [a3, a4]])
X = sympy.Matrix([[x1, x2], [x3, x4]])

# Definimos la Funcion Vectorial

fn = X @ A @ X

# Calculamos la Jacobiana Simbolica 

jacobian_symbolic_teory_1 = sympy.Matrix.zeros(X.shape[0] * fn.shape[0], X.shape[1] * fn.shape[1])
jacobian_symbolic_teory_2 = sympy.Matrix.zeros(X.shape[0] * fn.shape[0], X.shape[1] * fn.shape[1])

for row_output in range(fn.shape[0]):
    for col_output in range(fn.shape[1]):
        for row_input in range(X.shape[0]):
            for col_input in range(X.shape[1]):
                
                jacobian_row = row_output * fn.shape[1] + col_output
                jacobian_col = row_input * X.shape[1] + col_input
                
                jacobian_symbolic_teory_1[jacobian_row, jacobian_col] = sympy.Symbol(fr"\frac{{\partial F_{{{col_output+1},{row_output+1}}}}}{{\partial X_{{{col_input+1},{row_input+1}}}}}")
                jacobian_symbolic_teory_2[jacobian_row, jacobian_col] = sympy.Symbol(fr"\frac{{\partial F_{{{col_output+1},{row_output+1}}}}}{{\partial {X[col_input, row_input]}}}")

jacobian_symbolic_latex_1 = r"\begin{bmatrix}" + r" \\[5pt]".join(" & ".join(str(jacobian_symbolic_teory_1[row, col]) for col in range(jacobian_symbolic_teory_1.shape[1]))
                                                                  for row in range(jacobian_symbolic_teory_1.shape[0])) + r"\end{bmatrix}"

jacobian_symbolic_latex_2 = r"\begin{bmatrix}" + r" \\[5pt]".join(" & ".join(str(jacobian_symbolic_teory_2[row, col]) for col in range(jacobian_symbolic_teory_2.shape[1]))
                                                                  for row in range(jacobian_symbolic_teory_2.shape[0])) + r"\end{bmatrix}"

# Calculamos la Jacobiana

jacobian = sympy.Matrix.zeros(fn.shape[0] * fn.shape[1], X.shape[0] * X.shape[1])

for row_output in range(fn.shape[0]):
    for col_output in range(fn.shape[1]):
        for row_input in range(X.shape[0]):
            for col_input in range(X.shape[1]):
                
                jacobian_row = row_output * fn.shape[1] + col_output
                jacobian_col = row_input * X.shape[1] + col_input
                
                jacobian[jacobian_row, jacobian_col] = sympy.diff(fn[col_output, row_output], X[col_input, row_input])

# Calculamos la Jacobiana por Formula

I = sympy.Matrix.eye(X.shape[0])

jacobian_formula = sympy.kronecker_product(I, (X @ A)) + sympy.kronecker_product((A @ X).T, I)

# Visualizamos resultados

print('Funcion Vectorial:')
display(Math('F(X) = X \cdot A \cdot X'))
print(f'\n')
print('Definicion de Matrices:')
display(Math(f"A = {latex(A)}, \\quad X = {latex(X)}"))
print(f'\n')
print(f'Operacion #1:')
display(Math('C = X \cdot A'))
display(Math(f"C = {latex(X @ A)}"))
print(f'\n')
print(f'Salida de la Funcion Vectorial:')
display(Math('F(X) = C \cdot X'))
display(Math(f"F(X) = {latex(fn)}"))
print(f'\n')
print('Jacobiana Simbolica:')
display(Math(r"J_X = " + jacobian_symbolic_latex_1))
display(Math(r"J_X = " + jacobian_symbolic_latex_2))
display(Math(r"J_X = " + latex(jacobian)))
print(f'\n')
print('Jacobiana Formula:')
display(Math(r"J_X = I \otimes XA + (AX)^T \otimes I"))
display(Math(r"J_X = " + latex(jacobian_formula)))

Funcion Vectorial:


<IPython.core.display.Math object>



Definicion de Matrices:


<IPython.core.display.Math object>



Operacion #1:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Salida de la Funcion Vectorial:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Jacobiana Simbolica:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>



Jacobiana Formula:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [11]:
# Definimos Nuestra Matrices

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
A = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 

# Definimos la Funcion Vectorial

def Fn(X, A):   
    
    output = torch.matmul(X, A)
    output = torch.matmul(output, X)
    
    return output

# Calculamos la Matriz Jacobiana 

jacobian = jacrev(Fn, argnums = 0)(X, A)

# Redimensionamos (Cada sub-matrix de salida representa una columna de la matriz jacbianda definitiva)

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos un ejemplo numerico

print(f'La Jacobiana Respecto a X: \n{jacobian}')

La Jacobiana Respecto a X: 
tensor([[53., 23., 26.,  0.],
        [44., 90.,  0., 26.],
        [52.,  0., 56., 23.],
        [ 0., 52., 44., 93.]])


### **Ejercicio #3**

**Funcion:**

$$F(X) = XAX^T$$

**Derivada:**

$$d(X) = ((I \otimes XA) \cdot K_{m, n} + (AX^T)^T \otimes I) \cdot vec(dX)$$

**Jacobiana:** 

$$J = (I \otimes XA) \cdot K_{m, n} + (AX^T)^T \otimes I$$

In [12]:
# Definimos los coeficientes de ambas matrices

a1, a2, a3, a4 = sympy.symbols(names = 'a_{1} a_{2} a_{3} a_{4}')
x1, x2, x3, x4 = sympy.symbols(names = 'x_{1} x_{2} x_{3} x_{4}')

# Definimos las matrices

A = sympy.Matrix([[a1, a2], [a3, a4]])
X = sympy.Matrix([[x1, x2], [x3, x4]])

# Definimos la Funcion Vectorial

fn = X @ A @ X.T

# Calculamos la Jacobiana Simbolica 

jacobian_symbolic_teory_1 = sympy.Matrix.zeros(X.shape[0] * fn.shape[0], X.shape[1] * fn.shape[1])
jacobian_symbolic_teory_2 = sympy.Matrix.zeros(X.shape[0] * fn.shape[0], X.shape[1] * fn.shape[1])

for row_output in range(fn.shape[0]):
    for col_output in range(fn.shape[1]):
        for row_input in range(X.shape[0]):
            for col_input in range(X.shape[1]):
                
                jacobian_row = row_output * fn.shape[1] + col_output
                jacobian_col = row_input * X.shape[1] + col_input
                
                jacobian_symbolic_teory_1[jacobian_row, jacobian_col] = sympy.Symbol(fr"\frac{{\partial F_{{{col_output+1},{row_output+1}}}}}{{\partial X_{{{col_input+1},{row_input+1}}}}}")
                jacobian_symbolic_teory_2[jacobian_row, jacobian_col] = sympy.Symbol(fr"\frac{{\partial F_{{{col_output+1},{row_output+1}}}}}{{\partial {X[col_input, row_input]}}}")

jacobian_symbolic_latex_1 = r"\begin{bmatrix}" + r" \\[5pt]".join(" & ".join(str(jacobian_symbolic_teory_1[row, col]) for col in range(jacobian_symbolic_teory_1.shape[1]))
                                                                  for row in range(jacobian_symbolic_teory_1.shape[0])) + r"\end{bmatrix}"

jacobian_symbolic_latex_2 = r"\begin{bmatrix}" + r" \\[5pt]".join(" & ".join(str(jacobian_symbolic_teory_2[row, col]) for col in range(jacobian_symbolic_teory_2.shape[1]))
                                                                  for row in range(jacobian_symbolic_teory_2.shape[0])) + r"\end{bmatrix}"

# Calculamos la Jacobiana

jacobian = sympy.Matrix.zeros(fn.shape[0] * fn.shape[1], X.shape[0] * X.shape[1])

for row_output in range(fn.shape[0]):
    for col_output in range(fn.shape[1]):
        for row_input in range(X.shape[0]):
            for col_input in range(X.shape[1]):
                
                jacobian_row = row_output * fn.shape[1] + col_output
                jacobian_col = row_input * X.shape[1] + col_input
                
                jacobian[jacobian_row, jacobian_col] = sympy.diff(fn[col_output, row_output], X[col_input, row_input])

# Calculamos la Jacobiana por Formula (Recordamos cuando aparezca dX.T, tenemos que reorganizar la matriz)

I = sympy.Matrix.eye(X.shape[0])

n = A.shape[0]
m = X.shape[1]

commuted_indices = sympy.Matrix([[i + j*n for i in range(m)] for j in range(n)]).T

term_1 = sympy.kronecker_product(I, (X @ A))
term1_commuted = term_1[:, commuted_indices]

jacobian_formula = term1_commuted + sympy.kronecker_product((A @ X.T).T, I)

# Visualizamos resultados

print('Funcion Vectorial:')
display(Math('F(X) = X \cdot A \cdot X^T'))
print(f'\n')
print('Definicion de Matrices:')
display(Math(f"A = {latex(A)}, \\quad X = {latex(X)}"))
print(f'\n')
print(f'Operacion #1:')
display(Math('C = X \cdot A'))
display(Math(f"C = {latex(X @ A)}"))
print(f'\n')
print(f'Salida de la Funcion Vectorial:')
display(Math('F(X) = C \cdot X^T'))
display(Math(f"F(X) = {latex(fn)}"))
print(f'\n')
print('Jacobiana Simbolica:')
display(Math(r"J_X = " + gradient_symbolic_latex_1))
display(Math(r"J_X = " + gradient_symbolic_latex_2))
display(Math(r"J_X = " + latex(jacobian)))
print(f'\n')
print('Jacobiana Formula:')
display(Math(r"J_X = (I \otimes XC) \cdot K_{m, n} + (CX^T)^T \otimes I"))
display(Math(r"J_X = " + latex(jacobian_formula)))

Funcion Vectorial:


<IPython.core.display.Math object>



Definicion de Matrices:


<IPython.core.display.Math object>



Operacion #1:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Salida de la Funcion Vectorial:


<IPython.core.display.Math object>

<IPython.core.display.Math object>



Jacobiana Simbolica:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>



Jacobiana Formula:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [13]:
# Definimos Nuestras Matrices

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
A = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 

# Definimos la Funcion Vectorial

def Fn(X, A):   
    
    output = torch.matmul(X, A)
    output = torch.matmul(output, X.T)
    
    return output

# Calculamos la Matriz Jacobiana 

jacobian = jacrev(Fn, argnums = 0)(X, A)

# Redimensionamos (Cada sub-matrix de salida representa una columna de la matriz jacbianda definitiva)

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos un ejemplo numerico

print(f'La Jacobiana Respecto a X: \n{jacobian}')

La Jacobiana Respecto a X: 
tensor([[ 44.,   0.,  42.,   0.],
        [ 44.,  26.,  55.,  19.],
        [ 60.,  18.,  43.,  23.],
        [  0., 104.,   0.,  98.]])
