# **Librerias**

In [1]:
# Importamos

import jax
import torch
import warnings
import jax.numpy as jaxnp

from torch.func import jacfwd

# Logging 

warnings.filterwarnings('ignore', category = UserWarning)

# Version 

print(f'JAX Version: {jax.__version__}')
print(f'Pytorch Version: {torch.__version__}')

JAX Version: 0.4.34
Pytorch Version: 2.5.0+cpu


# **Jacobiana** 

### **Ejercicio #1**

**Funcion:**

$$F(X) = X^2$$

**Artificios:** 

$$X^2 = XX$$
$$vec(ABC) = (C^T \otimes A) \cdot vec(B)$$

**Derivada:**

$$d(X^2) = X dX + dX  X$$
$$d(X^2) = X  dX  I + I  dX  X$$
$$d(X^2) = vec(XdXI) + vec(IdXX)$$
$$d(X^2) = (I \otimes X) \cdot vec(dX) + (X^T \otimes I) \cdot vec(dX)$$
$$d(X^2) = (I \otimes X + X^T \otimes I) \cdot vec(dX)$$

**Jacobiana:** 

$$J = I \otimes X + X^T \otimes I$$

In [2]:
# Definimos la funcion matricial

def Fn(X):   
    
    output = torch.matmul(X, X)
    
    return output

# Definimos nuestra matriz de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jacfwd(Fn, argnums = 0)(X)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[2., 2., 3., 0.],
        [3., 5., 0., 3.],
        [2., 0., 5., 2.],
        [0., 2., 3., 8.]])


In [3]:
# Definimos la funcion matricial

def Fn(X):   
    
    output = jaxnp.matmul(X, X)
    
    return output

# Definimos nuestra matriz de ejemplo

X = jaxnp.array([[1.0, 2.0], [3.0, 4.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jax.jacfwd(Fn, argnums = 0)(X)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jaxnp.moveaxis(jacobian.T, (0, 1, 2, 3), (2, 3, 0, 1)).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
[[2. 2. 3. 0.]
 [3. 5. 0. 3.]
 [2. 0. 5. 2.]
 [0. 2. 3. 8.]]


In [4]:
# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
I = torch.eye(2) 

# Producto Kronecker

jacobian = torch.kron(I, X) + torch.kron(X.T.contiguous(), I)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[2., 2., 3., 0.],
        [3., 5., 0., 3.],
        [2., 0., 5., 2.],
        [0., 2., 3., 8.]])


### **Ejercicio #2**

**Funcion:**

$$F(X) = XCX$$

**Artificios:** 

$$vec(ABC) = (C^T \otimes A) \cdot vec(B)$$

**Derivada:**

$$d(XCX) = XCdX + XdCX + dXCX$$
$$d(XCX) = XCdXI + IdXCX$$
$$d(XCX) = vec(XCdXI) + vec(IdXCX)$$
$$d(XCX) = (I \otimes XC) \cdot vec(dX) + ((CX)^T \otimes I) \cdot vec(dX)$$
$$d(XCX) = (I \otimes XC + (CX)^T \otimes I) \cdot vec(dX)$$

**Jacobiana:** 

$$J = I \otimes XC + (CX)^T \otimes I$$

In [5]:
# Definimos la funcion matricial

def Fn(X, C):   
    
    output = torch.matmul(X, C)
    output = torch.matmul(output, X)
    
    return output

# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
C = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jacfwd(Fn, argnums = 0)(X, C)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[53., 23., 26.,  0.],
        [44., 90.,  0., 26.],
        [52.,  0., 56., 23.],
        [ 0., 52., 44., 93.]])


In [6]:
# Definimos la funcion matricial

def Fn(X, C):   
    
    output = jaxnp.matmul(X, C)
    output = jaxnp.matmul(output, X)
    
    return output

# Definimos nuestras matrices de ejemplo

X = jaxnp.array([[1.0, 2.0], [3.0, 4.0]]) 
C = jaxnp.array([[8.0, 9.0], [5.0, 7.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jax.jacfwd(Fn, argnums = 0)(X, C)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jaxnp.moveaxis(jacobian.T, (0, 1, 2, 3), (2, 3, 0, 1)).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
[[53. 23. 26.  0.]
 [44. 90.  0. 26.]
 [52.  0. 56. 23.]
 [ 0. 52. 44. 93.]]


In [7]:
# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
C = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 
I = torch.eye(2) 

# Producto Kronecker

jacobian = torch.kron(I, torch.matmul(X, C)) + torch.kron(torch.matmul(C, X).T.contiguous(), I)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[53., 23., 26.,  0.],
        [44., 90.,  0., 26.],
        [52.,  0., 56., 23.],
        [ 0., 52., 44., 93.]])


### **Ejercicio #3**


**Funcion:**

$$F(X) = AXB$$

**Artificios:** 

$$vec(ABC) = (C^T \otimes A) \cdot vec(B)$$

**Derivada:**

$$d(AXB) = AXdB + AdXB + dAXB$$
$$d(AXB) = AdXB$$
$$d(AXB) = vec(AdXB)$$
$$d(AXB) = (B^T \otimes A) \cdot vec(dX)$$

**Jacobiana:** 

$$J = B^T \otimes A$$

In [8]:
# Definimos la funcion matricial

def Fn(A, X, B):   
    
    output = torch.matmul(A, X)
    output = torch.matmul(output, B)
    
    return output

# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
A = torch.tensor([[8.0, 9.0], [5.0, 7.0], [9.0, 5.0]]) 
B = torch.tensor([[8.0, 9.0, 6.0], [5.0, 7.0, 1.0]])

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el segundo argumento 1 --> X) (forward-mode)

jacobian = jacfwd(Fn, argnums = 1)(A, X, B)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[64., 72., 40., 45.],
        [40., 56., 25., 35.],
        [72., 40., 45., 25.],
        [72., 81., 56., 63.],
        [45., 63., 35., 49.],
        [81., 45., 63., 35.],
        [48., 54.,  8.,  9.],
        [30., 42.,  5.,  7.],
        [54., 30.,  9.,  5.]])


In [9]:
# Definimos la funcion matricial

def Fn(A, X, B):   
    
    output = jaxnp.matmul(A, X)
    output = jaxnp.matmul(output, B)
    
    return output

# Definimos nuestras matrices de ejemplo

X = jaxnp.array([[1.0, 2.0], [3.0, 4.0]]) 
A = jaxnp.array([[8.0, 9.0], [5.0, 7.0], [9.0, 5.0]]) 
B = jaxnp.array([[8.0, 9.0, 6.0], [5.0, 7.0, 1.0]])

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el segundo argumento 1 --> X) (forward-mode)

jacobian = jax.jacfwd(Fn, argnums = 1)(A, X, B)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jaxnp.moveaxis(jacobian.T, (0, 1, 2, 3), (2, 3, 0, 1)).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
[[64. 72. 40. 45.]
 [40. 56. 25. 35.]
 [72. 40. 45. 25.]
 [72. 81. 56. 63.]
 [45. 63. 35. 49.]
 [81. 45. 63. 35.]
 [48. 54.  8.  9.]
 [30. 42.  5.  7.]
 [54. 30.  9.  5.]]


In [10]:
# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
A = torch.tensor([[8.0, 9.0], [5.0, 7.0], [9.0, 5.0]]) 
B = torch.tensor([[8.0, 9.0, 6.0], [5.0, 7.0, 1.0]])

# Producto Kronecker

jacobian = torch.kron(B.T.contiguous(), A) 

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[64., 72., 40., 45.],
        [40., 56., 25., 35.],
        [72., 40., 45., 25.],
        [72., 81., 56., 63.],
        [45., 63., 35., 49.],
        [81., 45., 63., 35.],
        [48., 54.,  8.,  9.],
        [30., 42.,  5.,  7.],
        [54., 30.,  9.,  5.]])


### **Ejercicio #4**

**Funcion:**

$$F(X) = XAX^TB$$

**Artificios:** 

$$vec(ABC) = (C^T \otimes A) \cdot vec(B)$$
$$vec(dX^T) = K_{m, n} \cdot vec(dX)$$

**Derivada:**

$$d(XAX^TB) = XAX^TdB + XAdX^TB + XdAX^TB + dXAX^TB$$
$$d(XAX^TB) = XAdX^TB + dXAX^TB$$
$$d(XAX^TB) = vec(XAdX^TB) + vec(dXAX^TB)$$
$$d(XAX^TB) = (B^T \otimes XA) \cdot vec(dX^T) + ((AX^TB)^T \otimes I) \cdot vec(dX)$$
$$d(XAX^TB) = (B^T \otimes XA) \cdot K_{m, n} \cdot vec(dX) + ((AX^TB)^T \otimes I) \cdot vec(dX)$$
$$d(XAX^TB) = ((B^T \otimes XA) \cdot K_{m, n} +  ((AX^TB)^T \otimes I))\cdot vec(dX)$$

**Jacobiana:** 

$$J = (B^T \otimes XA) \cdot K_{m, n} +  (AX^TB)^T \otimes I$$

In [11]:
# Definimos la funcion matricial

def Fn(A, X, B):   
    
    output = torch.matmul(X, A)
    output = torch.matmul(output, X.T)
    output = torch.matmul(output, B)
    
    return output

# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0], [9.0, 5.0]]) 
A = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 
B = torch.tensor([[8.0, 9.0, 6.0], [5.0, 7.0, 1.0], [7.0, 6.0, 4.0]])

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el segundo argumento 1 --> X) (forward-mode)

jacobian = jacfwd(Fn, argnums = 1)(A, X, B)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[1471.,   90.,  126., 1111.,  115.,  161.],
        [ 352., 1547.,  308.,  440., 1202.,  385.],
        [ 776.,  485., 2006.,  928.,  580., 1739.],
        [1518.,  126.,  108., 1159.,  161.,  138.],
        [ 396., 1664.,  264.,  495., 1337.,  330.],
        [ 873.,  679., 1938., 1044.,  812., 1648.],
        [ 792.,   18.,   72.,  615.,   23.,   92.],
        [ 264.,  728.,  176.,  330.,  532.,  220.],
        [ 582.,   97., 1072.,  696.,  116.,  941.]])


In [12]:
# Definimos la funcion matricial

def Fn(A, X, B):   
    
    output = jaxnp.matmul(X, A)
    output = jaxnp.matmul(output, X.T)
    output = jaxnp.matmul(output, B)
    
    return output

# Definimos nuestras matrices de ejemplo

X = jaxnp.array([[1.0, 2.0], [3.0, 4.0], [9.0, 5.0]]) 
A = jaxnp.array([[8.0, 9.0], [5.0, 7.0]]) 
B = jaxnp.array([[8.0, 9.0, 6.0], [5.0, 7.0, 1.0], [7.0, 6.0, 4.0]])

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el segundo argumento 1 --> X) (forward-mode)

jacobian = jax.jacfwd(Fn, argnums = 1)(A, X, B)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jaxnp.moveaxis(jacobian.T, (0, 1, 2, 3), (2, 3, 0, 1)).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
[[1471.   90.  126. 1111.  115.  161.]
 [ 352. 1547.  308.  440. 1202.  385.]
 [ 776.  485. 2006.  928.  580. 1739.]
 [1518.  126.  108. 1159.  161.  138.]
 [ 396. 1664.  264.  495. 1337.  330.]
 [ 873.  679. 1938. 1044.  812. 1648.]
 [ 792.   18.   72.  615.   23.   92.]
 [ 264.  728.  176.  330.  532.  220.]
 [ 582.   97. 1072.  696.  116.  941.]]


In [13]:
# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0], [9.0, 5.0]]) 
A = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 
B = torch.tensor([[8.0, 9.0, 6.0], [5.0, 7.0, 1.0], [7.0, 6.0, 4.0]])

I = torch.eye(3)

# Producto Kronecker

term_1 = torch.kron(B.T.contiguous(), torch.matmul(X, A)) 
term_2 = torch.kron(torch.matmul(torch.matmul(A, X.T.contiguous()), B).T.contiguous(), I)

# Conmutamos ya que existe vec(dX.T)

n = B.shape[0]
m = X.shape[1] 

commuted_indices = torch.arange(n * m).reshape(n, m).T.reshape(-1)

term1_commuted = term_1[:, commuted_indices]

# Calculamos el Jacobiano

jacobian = term1_commuted.reshape(term_1.shape) + term_2

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[1471.,   90.,  126., 1111.,  115.,  161.],
        [ 352., 1547.,  308.,  440., 1202.,  385.],
        [ 776.,  485., 2006.,  928.,  580., 1739.],
        [1518.,  126.,  108., 1159.,  161.,  138.],
        [ 396., 1664.,  264.,  495., 1337.,  330.],
        [ 873.,  679., 1938., 1044.,  812., 1648.],
        [ 792.,   18.,   72.,  615.,   23.,   92.],
        [ 264.,  728.,  176.,  330.,  532.,  220.],
        [ 582.,   97., 1072.,  696.,  116.,  941.]])


### **Ejercicio #5**

**Funcion:**

$$F(X) = XCX^T$$

**Artificios:** 

$$vec(ABC) = (C^T \otimes A) \cdot vec(B)$$
$$vec(dX^T) = K_{m, n} \cdot vec(dX)$$

**Derivada:**

$$d(XCX^T) = XCdX^T + XdCX^T + dXCX^T$$
$$d(XCX^T) = XCdX^TI + IdXCX^T$$
$$d(XCX^T) = vec(XCdX^TI) + vec(IdXCX^T)$$
$$d(XCX^T) = (I \otimes XC) \cdot vec(dX^T) + ((CX^T)^T \otimes I) \cdot vec(dX)$$
$$d(XCX^T) = (I \otimes XC) \cdot K_{m, n} \cdot vec(dX) + ((CX^T)^T \otimes I) \cdot vec(dX)$$
$$d(XCX^T) = ((I \otimes XC) \cdot K_{m, n} + (CX^T)^T \otimes I) \cdot vec(dX)$$

**Jacobiana:** 

$$J = (I \otimes XC) \cdot K_{m, n} + (CX^T)^T \otimes I$$

In [14]:
# Definimos la funcion matricial

def Fn(X, C):   
    
    output = torch.matmul(X, C)
    output = torch.matmul(output, X.T)
    
    return output

# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
C = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jacfwd(Fn, argnums = 0)(X, C)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[ 44.,   0.,  42.,   0.],
        [ 44.,  26.,  55.,  19.],
        [ 60.,  18.,  43.,  23.],
        [  0., 104.,   0.,  98.]])


In [15]:
# Definimos la funcion matricial

def Fn(X, C):   
    
    output = jaxnp.matmul(X, C)
    output = jaxnp.matmul(output, X.T)
    
    return output

# Definimos nuestras matrices de ejemplo

X = jaxnp.array([[1.0, 2.0], [3.0, 4.0]]) 
C = jaxnp.array([[8.0, 9.0], [5.0, 7.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jax.jacfwd(Fn, argnums = 0)(X, C)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jaxnp.moveaxis(jacobian.T, (0, 1, 2, 3), (2, 3, 0, 1)).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
[[ 44.   0.  42.   0.]
 [ 44.  26.  55.  19.]
 [ 60.  18.  43.  23.]
 [  0. 104.   0.  98.]]


In [16]:
# Definimos nuestras matrices de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 
C = torch.tensor([[8.0, 9.0], [5.0, 7.0]]) 

I = torch.eye(2)

# Producto Kronecker

term_1 = torch.kron(I, torch.matmul(X, C)) 
term_2 = torch.kron(torch.matmul(C, X.T.contiguous()).T.contiguous(), I)

# Conmutamos ya que existe vec(dX.T)

n = C.shape[0]
m = X.shape[1] 

commuted_indices = torch.arange(n * m).reshape(n, m).T.reshape(-1)

term1_commuted = term_1[:, commuted_indices]

# Calculamos el Jacobiano

jacobian = term1_commuted.reshape(term_1.shape) + term_2

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[ 44.,   0.,  42.,   0.],
        [ 44.,  26.,  55.,  19.],
        [ 60.,  18.,  43.,  23.],
        [  0., 104.,   0.,  98.]])


### **Ejercicio #6**

**Funcion:**

$$F(X) = X^{-1}$$

**Artificios:** 

$$vec(ABC) = (C^T \otimes A) \cdot vec(B)$$

$$I = XX^{-1}$$
$$dI = XdX^{-1} + dXX^{-1}$$
$$0 = XdX^{-1} + dXX^{-1}$$
$$XdX^{-1} = - (dXX^{-1})$$
$$X^{-1}XdX^{-1} = - (X^{-1}dXX^{-1})$$
$$dX^{-1} = - (X^{-1}dXX^{-1})$$

**Derivada:**

$$d(X^{-1}) = dX^{-1}$$
$$d(X^{-1}) = - (X^{-1}dXX^{-1})$$
$$d(X^{-1}) = - vec(X^{-1}dXX^{-1})$$
$$d(X^{-1}) = ((X^{-1})^T \otimes X^{-1}) \cdot vec(dX)$$

**Jacobiana:** 

$$J = (X^{-1})^T \otimes X^{-1}$$

In [17]:
# Definimos la funcion matricial

def Fn(X):   
    
    output = torch.linalg.inv(X)
    
    return output

# Definimos nuestra matriz de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jacfwd(Fn, argnums = 0)(X)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jacobian.T.permute(2, 3, 0, 1).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[-4.0000,  2.0000,  3.0000, -1.5000],
        [ 3.0000, -1.0000, -2.2500,  0.7500],
        [ 2.0000, -1.0000, -1.0000,  0.5000],
        [-1.5000,  0.5000,  0.7500, -0.2500]])


In [18]:
# Definimos la funcion matricial

def Fn(X):   
    
    output = jaxnp.linalg.inv(X)
    
    return output

# Definimos nuestra matriz de ejemplo

X = jaxnp.array([[1.0, 2.0], [3.0, 4.0]]) 

# Calculamos la Matriz Jacobiana (Indicamos con respecto a que argumento derivamos en nuestro caso el primer argumento 0 --> X) (forward-mode)

jacobian = jax.jacfwd(Fn, argnums = 0)(X)

# Redimensionamos

new_shape = (jacobian.shape[0] * jacobian.shape[1], jacobian.shape[2] * jacobian.shape[3])

jacobian = jaxnp.moveaxis(jacobian.T, (0, 1, 2, 3), (2, 3, 0, 1)).reshape(new_shape)

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
[[-4.000001    2.0000005   3.0000007  -1.5000004 ]
 [ 3.0000007  -1.0000002  -2.2500005   0.7500002 ]
 [ 2.0000005  -1.0000002  -1.0000002   0.5000001 ]
 [-1.5000004   0.5000001   0.7500002  -0.25000006]]


In [19]:
# Definimos nuestra matriz de ejemplo

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) 

# Producto Kronecker

jacobian = - torch.kron((torch.linalg.inv(X).contiguous()).T.contiguous(), torch.linalg.inv(X).contiguous()) 

# Visualizamos

print(f'El Jacobiano Respecto a X: \n{jacobian}')

El Jacobiano Respecto a X: 
tensor([[-4.0000,  2.0000,  3.0000, -1.5000],
        [ 3.0000, -1.0000, -2.2500,  0.7500],
        [ 2.0000, -1.0000, -1.0000,  0.5000],
        [-1.5000,  0.5000,  0.7500, -0.2500]])
